pipeline {
	agent any

	stages {
		stage('Unit Tests Backend') {
			agent {
				docker {
					image 'snakee/golang-junit:1.21'
					reuseNode true
				}
			}
			environment {
				XDG_CACHE_HOME = '/tmp/.cache'
				GOMODCACHE = '/tmp/go-mod-cache'
			}
			steps {
				dir('bugtracker-backend') {
					sh 'go test -v ./...'
				}
			}
		}
	}
}