name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5

        - name: Set up Go
          uses: actions/setup-go@v6
          with:
            go-version: '1.20'
            cache-dependency-path: bugtracker-backend/go.sum

        - name: Execute Backend Unit Tests
          working-directory: ./bugtracker-backend
          run: |
            go test -v ./...